
Epoch:  0 Train loss is:  5.197525029504126 VAl loss is:  6.313798805306848
Traceback (most recent call last):
  File "cilrs_train.py", line 135, in <module>
    main()
  File "cilrs_train.py", line 129, in main
    print('Epoch: ', i, 'Train loss is: ', train(model, train_loader), 'VAl loss is: ', validate(model, val_loader) )
  File "cilrs_train.py", line 22, in validate
    for measurements,image in dataloader:
  File "/kuacc/users/ajamshidi18/.conda/envs/driving2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/kuacc/users/ajamshidi18/.conda/envs/driving2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/kuacc/users/ajamshidi18/.conda/envs/driving2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/kuacc/users/ajamshidi18/.conda/envs/driving2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/scratch/users/ajamshidi18/hpc_run/AutoDriving/hw1/expert_dataset.py", line 25, in __getitem__
    rgb = image.convert("RGB")
  File "/kuacc/users/ajamshidi18/.conda/envs/driving2/lib/python3.7/site-packages/PIL/Image.py", line 933, in convert
    self.load()
  File "/kuacc/users/ajamshidi18/.conda/envs/driving2/lib/python3.7/site-packages/PIL/ImageFile.py", line 269, in load
    n, err_code = decoder.decode(b)
KeyboardInterrupt